version: '3'
services:
  mailhog:   
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mailhog-{{vm_name}}
    image: mailhog/mailhog
    environment:
    - MH_STORAGE=maildir
    - MH_MAILDIR_PATH=/maildir
    - MH_AUTH_FILE=/auth/auth.txt
    volumes:
    - ./maildir:/maildir
    #- ./tmp:/tmp
    - ./auth.txt:/auth/auth.txt
    ports:
    - "{{smtp_port}}:1025"
    - "{{ui_port}}:8025"