version: '3'
services:
    wordpress:
        image: wordpress
        links:
         - mariadb:mysql
        environment:
         - WORDPRESS_DB_PASSWORD=secret
         - WORDPRESS_DB_USER=root
        ports:
         - "8081:80"
        volumes:
         - ./html:/var/www/html
    mariadb:
        image: mariadb
        environment:
         - MYSQL_ROOT_PASSWORD=secret
         - MYSQL_DATABASE=wordpress
        volumes:
         - ./database:/var/lib/mysql